backend:
  name: git-gateway 
local_backend: true # https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "test-json" 
    label: "Test de JSON" # Used in the UI
    folder: "src/assets/test-json" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    extension : "json"
    fields: # The fields for each document, usually in front matter
      - {label: "ID", name: "id", widget: "uuid"} # utilise https://www.npmjs.com/package/netlify-cms-widget-uuid-v4
      # - {label: "ID", name: "id", widget: "number", value_type: "int"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}